server:
  port: 9002

spring:
  application:
    name: auth


  profiles:
    include: common_util_dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

  instance:
    instance-id: 网关服务-9001
    prefer-ip-address: true

zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: service-auth
    general:
      path: /general/**
      serviceId: service-general
    play:
      path: /play/**
      serviceId: service-play

ribbon:
  eureka:
    enabled: false #禁止使用Eureka中集成的负载均衡