server:
  port: 9004

spring:
  application:
    name: biz-service

  # 多个接口上的@FeignClient(“相同服务名”)会报错，overriding is disabled。
  # 设置 为true ,即 允许 同名
  main:
    allow-bean-definition-overriding: true

  redis:
    host: 127.0.0.1
    port: 6379
    # REDIS (RedisProperties)
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器连接密码（默认为空）
    #    password:
    # 连接池最大连接数（使用负值表示没有限制）
    # 连接超时时间（毫秒）
    timeout: 500
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 20
        min-idle: 0
    #    pool:
  #      max-active: 8
  #      # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #      max-wait: -1
  #      # 连接池中的最大空闲连接
  #      max-idle: 8
  #      # 连接池中的最小空闲连接
  #      min-idle: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

  instance:
    instance-id: 业务服务-9004
    prefer-ip-address: true

